name: ASH Security Scan

on:
  pull_request:
    branches:
      - ash-poc
  push:
    branches:
      - ash-poc

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  ash_scan:
    name: ash_scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ASH Scan (CI)
        run: |
          chmod +x security/run_ash.sh
          security/run_ash.sh
